//
// Created by 17851 on 2024/3/26.
//

#ifndef UNTITLED1_STATIC_USER_ACTION_H
#define UNTITLED1_STATIC_USER_ACTION_H
#define ALLOW_CREATE_STUDENT 1
#define ALLOW
#endif //UNTITLED1_STATIC_USER_ACTION_H
